node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
       nodejs('Nodejs') {
         sh 'npm install --only=dev --no-bin-links'
         sh 'npm test --no-bin-links'
          }
   }
   stage('docker build/push') {
     withDockerRegistry(credentialsId: '3d937e99-1e83-4f2a-b415-deb6bd91ee4e', url: 'https://cloud.docker.com/repository/registry-1.docker.io/') {
       def app = docker.build("varun454/testrepo/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
