node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test')
   { 
    nodejs('Nodejs') {
      sh 'npm install --only=dev --no-bin-links'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://cloud.docker.com/u/varun454/repository/docker/varun454/','Dockerjenkin') {
       def app = docker.build("testrepo/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
